### ISSUE TITLE
Add a service/epackage token for Capella

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/Capella-Extensions#19]
Add a service/epackage token for Capella:
- all epackages *capella*
- services specific to Capella for instance #18

**Comment by ylussaud** [comment]
Some services might already exists in Capella's odesigns. See *Ext classes for instance ComponentExt.

**Comment by ejuliot** [comment]
These services are available there : https://git.polarsys.org/c/capella/capella.git/tree/core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers
