### ISSUE TITLE
Wrong URI when selection "Sirius" in the template configuration

### ISSUE THREAD

**Issue by stephanelacrampe** [ObeoNetwork/Capella-Extensions#26]
When selecting the "Sriius" checkbox in the template configruation of a M2Doc template, it adds automatically a list of NsURIs.
But is adds http://www.eclipse.org/sirius/tree/1.1.0 instead of http://www.eclipse.org/sirius/tree/1.0.0

**Comment by ylussaud** [comment]
The metamodels from Sirius as been added to the Capella token. I'll will remove the Sirius token since the only way to keep it synchronized would be to add it to Sirius, probably creating a circular dependency.
