### ISSUE TITLE
Non headless behavior when an error araise with the command line generation

### ISSUE THREAD

**Issue by ylussaud** [ObeoNetwork/Capella-Extensions#29]
At some point a dialog is opened and need some interaction.

**Comment by ylussaud** [comment]
I was not able to reproduce this issue:

Using Capella 5.1.0, M2Doc 3.2.0, and M2Doc extensions for Capella 5.1.0 (all under dev currently):

- import the IFE example from M2Doc extensions for Capella and update the model to Capella 5.1.0
- remove the service import from the SA template to produce an error
- run the command line with -appid org.obeonetwork.capella.m2doc.commandline -filepath "In-Flight Entertainment System With M2Doc/Template SA Complete.genconf"

I get the following output and was not prompted and the process terminated:

```
....
Output: platform:/resource/In-Flight%20Entertainment%20System%20With%20M2Doc/generated/SA_Complete.docx
Output: platform:/resource/In-Flight%20Entertainment%20System%20With%20M2Doc/generated/SA_Complete-error.docx
...

```

Same result with M2Doc 3.1.1, M2doc extensions for Capella 5.0.0 and Capella 5.0.0.

**Comment by UweThales** [comment]
We are using Melody 4.5.2 (=Capella 1.4.2) and M2Doc 3.1.1.

The root case for the error is that there is an issue with the jsoup bundle and 'fromHTMLBodyString' does not work.
But, the issue here is not this error, but that it triggers an interactive window.

Find attached the log
[melody-log.txt](https://github.com/ObeoNetwork/Capella-Extensions/files/6334018/melody-log.txt)

**Comment by ylussaud** [comment]
OK so this dialog might not come from M2Doc at all. I'm also working on the jsoup issue. I'll leave this open in the mean time.

**Comment by UweThales** [comment]
OK.
FYI, related to the jsoup topic, there is an Thales internal ticket open and I am waiting for feedback (not sure if you were contacted).

**Comment by ylussaud** [comment]
I was, I made some modifications and I'm waiting for feedback from Thales.

**Comment by UweThales** [comment]
I could now fix the jsoup issue by installing the M2Doc Capella extensions as dropin.

But, I still have this issue: always if the document generation produces an error, e.g. because there is a coding mistake in the template, the command line generation prompts the Error window.

I just noticed that it obviously depends on the type of error, which is produced. I will try to find out, for which type of error it happens.

**Comment by UweThales** [comment]
I am able to produce the error e.g. if I use an **invalid filepath argument**:

Command-line arguments:  -os win32 -ws win32 -arch x86_64 -pluginCustomization pluginCustomization.ini -consolelog -application org.polarsys.capella.core.commandline.core -appid org.obeonetwork.capella.m2doc.commandline **-filepath MyModel/template-not-existing.genconf** -data ....

There are other causes as well, but this one is easy to reproduce. 
The others I could not sort out.

**Comment by ylussaud** [comment]
I tried with a not existing variable and I don't reproduce with M2Doc 3.1.1, M2doc extensions for Capella 5.0.0 and Capella 5.0.0.
I tried with Capella 1.4.2 and M2Doc 3.1.1 under Linux and Window and it seems to work. The process end and the error document is generated, no user interaction needed. Under Windows the process run in background. I used the following command line:

eclipse.exe -os win32 -ws win32 -arch x86_64 -consolelog -application org.polarsys.capella.core.commandline.core -appid org.obeonetwork.capella.m2doc.commandline -filepath "In-Flight Entertainment System With M2Doc/Template SA Complete.genconf"

You probably have something specific in your pluginCustomization.ini that cause the issue. Can you try without the plugin customization option ?

**Comment by UweThales** [comment]
I removed the option '-pluginCustomization', but it is the same thing. 

Arent't you able to reproduce if you take a bad '-filepath' argument?
E.g. -filepath "In-Flight Entertainment System With M2Doc/**xxx**Template SA Complete.genconf" in your case?

**Comment by ylussaud** [comment]
When the genconf doesn't exists I have a generic dialog from Eclipse telling me to check the .log file.

**Comment by UweThales** [comment]
I was able to reproduce the issue for an M2Doc error now. It is happening during document generation:

>>> Generating .docx documents
Input: platform:/resource/ATO-OB_Core/m2docTemplates/ADD_RegulationLayer.genconf

!ENTRY com.thalesgroup.mde.melody.collab.ui 1 0 2021-04-27 03:21:22.346
!MESSAGE Team for Capella -> SESSION OPENING:Local Session: platform:/resource/ATO-OB_Core/ATO-OB_Core.aird

!ENTRY com.thalesgroup.mde.melody.collab.ui 1 0 2021-04-27 03:21:22.350
!MESSAGE Team for Capella -> SESSION OPENING

!ENTRY com.thalesgroup.mde.melody.collab.ui 1 0 2021-04-27 03:21:25.099
!MESSAGE Team for Capella -> SESSION OPENED:Local Session: platform:/resource/ATO-OB_Core/ATO-OB_Core.aird
>>> Parsing platform:/resource/ATO-OB_Core/m2docTemplates/ADD.template.docx
  > Loading template
  > Parsing template custom properties
  > Parsing template body
  > Parsing template footers
  > Parsing template headers
>>> Validating platform:/resource/ATO-OB_Core/m2docTemplates/ADD.template.docx
  > Initialize engine
  > Validating document
>>> Generating ADD_RegulationLayer.generated.docx
  > Initializing desination document
  > Initializing engine
  > Initializing template services
  > Generating

!ENTRY org.eclipse.osgi 4 0 2021-04-27 03:21:30.060
!MESSAGE Application error
!STACK 1
org.apache.xmlbeans.impl.values.XmlValueDisconnectedException
        at org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1258)
        at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTPImpl.removeR(Unknown Source)
        at org.apache.poi.xwpf.usermodel.XWPFParagraph.removeRun(XWPFParagraph.java:1605)
        at org.obeonetwork.m2doc.generator.BookmarkManager.startBookmark(BookmarkManager.java:114)
        at org.obeonetwork.m2doc.generator.M2DocEvaluator.insertMBookmark(M2DocEvaluator.java:754)
        at org.obeonetwork.m2doc.generator.M2DocEvaluator.insertObject(M2DocEvaluator.java:623)
        at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseQuery(M2DocEvaluator.java:593)
        at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseQuery(M2DocEvaluator.java:1)
        at org.obeonetwork.m2doc.template.util.TemplateSwitch.doSwitch(TemplateSwitch.java:186)
        at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:53)
        at org.eclipse.emf.ecore.util.Switch.doSwitch(Switch.java:69)
        at org.obeonetwork.m2doc.generator.M2DocEvaluator.doSwitch(M2DocEvaluator.java:1242)
        at org.obeonetwork.m2doc.generator.M2DocEvaluator.caseBlock(M2DocEvaluator.java:1467)

**Comment by ylussaud** [comment]
This problem is probably fixed in newer versions of M2Doc. Still we probably don't want this to open a dialog or anything similar. Do you have a screenshot a of the dialog ? So I can figure out where it's coming from.

**Comment by UweThales** [comment]
Find attached two error windows. One generated from command line execution; another one from GUI execution for the same genconf.

From command line execution:
![m2doc-commandline-2](https://user-images.githubusercontent.com/23117365/116206025-a69c3c80-a73e-11eb-8423-24262f9fd834.png)
In the logfile you find the stack trace I sent before.

From GUI execution:
![m2doc-gui-error](https://user-images.githubusercontent.com/23117365/116206019-a56b0f80-a73e-11eb-8769-1fd2d55e49f5.png)

**Comment by ylussaud** [comment]
Those dialogs are opened by the Eclipse platform. As a workaround one should make sure the specified genconf file exists. It might also be related to #30 since the NPE was maybe producing this behavior.
