### ISSUE TITLE
Promote archived update sites

### ISSUE THREAD

**Issue by ymortier** [ObeoNetwork/Capella-Extensions#8]
Update sites for:

- Capella Extensions
- Capella Extensions and dependencies

are promoted on the s3 amazon server. It can be very useful to upload an archived version of those update sites for people who can't install features from a remote update site.

**Comment by ylussaud** [comment]
This has been fixed in commit 3a5eff0dd7290c70a910268508f589caf6afaf56 and commit 8629844eba088a06f75acae87b3de3de1da2696b.
